export const EVENTS = {
  ONLINE_DATA_UPDATE: 'online-data-update',
  THEME_CHANGE: 'theme-change',
  MENU_SELECT: 'menu-select',
  RETURN_TO_MAP: 'return-to-map',
  PILOT_SCHEMA_CHANGE: 'pilot-schema-change',
  PILOT_ICON_CLICK: 'pilot-icon-click',
  PILOT_INFO_CLOSE: 'pilot-info-close',
  NAVDATA_UPDATE: 'navdata-update',
  TOGGLE_3D_TRACK: 'toggle-3d-track',
  PILOT_POSITION_UPDATE: 'pilot-position-update',
  HISTORY_TRACK_UPDATE: 'history-track-update',
  PILOT_TRACK_DATA_UPDATE: 'pilot-track-data-update',
  AIRPORT_CLICK: 'airport-click',
  AIRPORT_INFO_CLOSE: 'airport-info-close',
  TOGGLE_FLIGHT_TRACKING: 'toggle-flight-tracking',
  STOP_FLIGHT_TRACKING: 'stop-flight-tracking',
  FLIGHT_SHARED: 'flight-shared',
  TOGGLE_WEATHER_RADAR: 'toggle-weather-radar',
  UPDATE_WEATHER_RADAR_OPACITY: 'update-weather-radar-opacity',
  MAP_STYLE_CHANGE: 'map-style-change',
  CONTROLLER_ICON_CLICK: 'controller-icon-click',
  CONTROLLER_INFO_CLOSE: 'controller-info-close',
  INSTALL_APP_CLICK: 'install-app-click'
}

export const MAP_IDS = {
  PILOT_LIST_SOURCE: 'pilot-list-data',
  PILOT_LIST_LAYER: 'pilot-list-data',
  SELECTED_PILOT_ROUTE_SOURCE: 'selected-pilot-route-data',
  SELECTED_PILOT_ROUTE_LAYER: 'selected-pilot-route-layer',
  PILOT_TRACK_2D_SOURCE: 'pilot-track-2d-data',
  PILOT_TRACK_2D_LAYER: 'pilot-track-2d-layer',
  PILOT_TRACK_3D_LAYER: 'detail-pilot-path-fill-3d',
  PREDICTED_TRAIL_SOURCE: 'predicted-trail-data',
  PREDICTED_TRAIL_LAYER: 'predicted-trail-layer',
  ACTIVE_AIRPORTS_SOURCE: 'active-airports-data',
  ACTIVE_AIRPORTS_LAYER: 'active-airports-layer',
  AIRPORT_RADIATION_SOURCE: 'airport-radiation-data',
  AIRPORT_RADIATION_LAYER: 'airport-radiation-layer',
  WEATHER_RADAR_SOURCE: 'weather-radar-data',
  WEATHER_RADAR_LAYER: 'weather-radar-layer',
  // Controller layers
  CONTROLLER_POLYGON_SOURCE: 'controller-polygon-data',
  CONTROLLER_POLYGON_FILL_LAYER: 'controller-polygon-fill',
  CONTROLLER_POLYGON_LINE_LAYER: 'controller-polygon-line',
  CONTROLLER_CIRCLE_SOURCE: 'controller-circle-data',
  CONTROLLER_CIRCLE_FILL_LAYER: 'controller-circle-fill',
  CONTROLLER_CIRCLE_LINE_LAYER: 'controller-circle-line',
  CONTROLLER_MARKER_SOURCE: 'controller-marker-data',
  CONTROLLER_MARKER_LAYER: 'controller-marker-layer'
}